#!/bin/sh

CC2L=../cpptolua

LOG=log.txt

echo "Generating $1.cpp" >> $LOG
if $CC2L -i $1.h >> $LOG 2>&1  ; then
	echo "$1.cpp PASSED"
else
	echo "$1.cpp FAILED"
fi

echo "Generating $1.h" >> $LOG
if $CC2L -i $1.h -H >> $LOG 2>&1  ; then
	echo "$1.h PASSED"
else
	echo "$1.h FAILED"
fi
