/*
	Lua bindings for class Cat
	This file was automatically generated by cpptolua

*/

#include "cat.h"

extern "C" {
	#include "lua.h"
	#include "lauxlib.h"
	#include "lualib.h"

}

int Cat_magic(lua_State* L);
int Cat_damage(lua_State* L);
int Cat_getPancakeMix(lua_State* L);
int Cat_setPancakeMix(lua_State* L);
int Cat_sleep(lua_State* L);
int Cat_query(lua_State* L);
int Cat_meow(lua_State* L);
int Cat_makeCake(lua_State* L);
int Cat_new(lua_State* L);
Cat* toCat(lua_State *L, int index);
Cat* checkCat(lua_State *L, int index);
int luaopen_Cat(lua_State *L);
